Repository torimons/torimon, pull requests merged in 2020-02, with the labels that each got.

#235 検索結果がある場合にspotInfoを非表示にする
  src/components/SpotSearch/index.ts
  tests/unit/components/SpotSearch/spotSearch.spec.ts
Labels: review request

#262 コンポーネントファイルの名前変更
  src/App.vue
  src/components/MainView/index.vue
  src/components/Map/index.vue
  src/components/MapView/GeolocationWrapper.ts
  src/components/MapView/Marker/CurrentLocationMarker.ts
  src/components/MapView/Marker/DefaultSpotMarker.ts
  src/components/MapView/index.ts
  src/components/MapView/index.vue
  src/components/SpotList/index.ts
  tests/unit/components/FloorSwitchButton/FloorSwitchButton.spec.ts
  tests/unit/components/MapView/MapUpdateIdOfCenterSpot.spec.ts
  tests/unit/components/MapView/defaultSpotMarker.spec.ts
  tests/unit/components/MapView/mapDisplayPolygons.spec.ts
  tests/unit/components/MapView/mapDisplayRouteLine.spec.ts
  tests/unit/components/MapView/mapMarkerSelect.spec.ts
  tests/unit/components/MapView/mapSwitchMarkers.spec.ts
  tests/unit/components/MapView/mapUpdateDisplayLevel.spec.ts
  tests/unit/components/MapView/selectMapToDisplay.spec.ts
  tests/unit/components/SpotList/spotList.spec.ts
Labels: Refactoring, review request

#263 SpotItemを選択時にSpotListを透過にする
  src/components/SpotSearch/index.ts
  tests/unit/components/SpotSearch/spotSearch.spec.ts
Labels: review request

#264 Spotクラス, Mapクラスの雛形作成
  src/Map/Map.ts
  src/Spot/Spot.ts
Labels: review request

#237 検索機能の追加
  src/utils/Search.ts
  tests/unit/utils/Search.spec.ts
Labels: enhancement
